version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.5-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: 'docker.io/bitnami/moodle:3-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
      - 'moodle_ml_data_data:/bitnami/moodle_ml_data'
      - '/Users/doug.morgan/.local/share/virtualenvs/moodle-mlbackend-python-J01hiJqW/bin:/bitnami/ml-backend'
      - '/usr/local/opt/python@3.7/bin:/usr/local/opt/python@3.7/bin'
    depends_on:
      - mariadb
  mlbackend:
    image: latest:latest
    ports:
      - '8080:80'
    environment:
      - MOODLE_MLBACKEND_PYTHON_USERS=default:sshhhh
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
      - 'moodle_ml_data_data:/bitnami/moodle_ml_data'
    depends_on:
      - moodle
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
  moodle_ml_data_data:
    driver: local
